# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_date'],
                'default_related_name': 'conferences',
            },
        ),
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('biography', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('blog', models.URLField(blank=True, default='')),
                ('twitter_handle', models.CharField(blank=True, default='', max_length=50)),
                ('irc_handle', models.CharField(blank=True, default='', max_length=50, verbose_name='IRC handle')),
                ('github_handle', models.CharField(blank=True, default='', max_length=50)),
                ('slack_handle', models.CharField(blank=True, default='', max_length=50)),
                ('business', models.CharField(blank=True, default='', max_length=200)),
                ('position', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['name'],
                'default_related_name': 'presenters',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
                'default_related_name': 'resources',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('video', models.URLField(blank=True, default='')),
                ('slides', models.FileField(blank=True, max_length=250, null=True, upload_to='slides')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeslots', to='conference.Conference')),
                ('presenters', models.ManyToManyField(blank=True, related_name='timeslots', to='conference.Presenter')),
                ('resources', models.ManyToManyField(blank=True, related_name='timeslots', to='conference.Resource')),
            ],
            options={
                'ordering': ['start_at'],
                'default_related_name': 'timeslots',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
                'default_related_name': 'venues',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='conference.Venue'),
        ),
        migrations.AddField(
            model_name='conference',
            name='venues',
            field=models.ManyToManyField(blank=True, related_name='conferences', to='conference.Venue'),
        ),
    ]
